FROM almalinux:9-minimal

LABEL org.opencontainers.image.title="afsbotcfg-fake-worker" \
      org.opencontainers.image.description="Buildbot fake worker for local testing" \
      org.opencontainers.image.authors="Michael Meffie" \
      org.opencontainers.image.source="https://github.com/openafs-contrib/afsbotcfg/podman/openafs-contrib/afsbotcfg-fake-worker"

RUN microdnf install -y python3 python3-setuptools python3-pip make gcc
RUN pip3 install buildbot-worker
RUN microdnf remove -y make gcc && \
    microdnf clean all

WORKDIR /app
COPY stubs/usr /usr/
COPY stubs/bin /bin/
COPY stubs/openafs /app/stubs/
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
