# OpenAFS buildbot master configuration.
---

afsbotcfg_project:
  name: "openafs"
  title: "OpenAFS Buildbot"
  summary_title: "The OpenAFS Buildbot Coordinator"
  db_url: "sqlite:///state.sqlite"
  url: "https://buildbot.openafs.org/"
  www_port: 8011
  pb_port: 9989
  email_from: "buildbot@openafs.MIT.EDU"
  repo: "git://gerrit.openafs.org/openafs.git"
  start_delay: 30
  # Long term branch names.
  branches:
    dev: "master"
    stable: "openafs-stable-1_8_x"
    oldstable: "openafs-stable-1_6_x"
  # Delete build logs older than four weeks on Sunday at 12:00PM (noon).
  janitor:
    log_horizon: 4
    day_of_week: 6
    hour: 12

afsbotcfg_gerrit:
  url: "https://gerrit.openafs.org"
  ident: "gerrit"
  hostkey: "gerrit.hostkey"
  user: "buildbot"
  server: "gerrit.openafs.org"
  ssh_port: 29418

afsbotcfg_workers:
  aix61-rs:
    owner: "Ben Huntsman <ben@huntsmans.net>"
  alma9-amd64:
    owner: "mmeffie@sinenomine.net"
  alma9-amd64-rpm:
    owner: "mmeffie@sinenomine.net"
  centos6-amd64:
    owner: "mmeffie@sinenomine.net"
  centos73-x86_64:
    owner: "mmeffie@sinenomine.net"
  centos7-arm64:
    owner: "mmeffie@sinenomine.net"
  centos8-amd64:
    owner: "mmeffie@sinenomine.net"
  debian10-amd64:
    owner: "mmeffie@sinenomine.net"
  debian11-amd64:
    owner: "mmeffie@sinenomine.net"
  debian87-x86_64:
    owner: "mmeffie@sinenomine.net"
  debian9-amd64:
    owner: "mmeffie@sinenomine.net"
  fedora21-x86_64:
    owner: "derek@ihtfp.com"
  fedora22-x86_64:
    owner: "derek@ihtfp.com"
  fedora23-x86_64:
    owner: "derek@ihtfp.com"
  fedora24-x86_64:
    owner: "derek@ihtfp.com"
  fedora25-x86_64:
    owner: "derek@ihtfp.com"
  fedora26-x86_64:
    owner: "derek@ihtfp.com"
  fedora27-x86_64:
    owner: "derek@ihtfp.com"
  fedora28-x86_64:
    owner: "derek@ihtfp.com"
  fedora29-x86_64:
    owner: "derek@ihtfp.com"
  fedora30-x86_64:
    owner: "derek@ihtfp.com"
  fedora31-x86_64:
    owner: "derek@ihtfp.com"
  fedora32-x86_64:
    owner: "derek@ihtfp.com"
  fedora33-x86_64:
    owner: "derek@ihtfp.com"
  fedora34-x86_64:
    owner: "derek@ihtfp.com"
  fedora35-x86_64:
    owner: "derek@ihtfp.com"
  freebsd11-amd64:
    owner: "mansaxel@besserwisser.org"
  freebsd12-amd64:
    owner: "mansaxel@besserwisser.org"
  freebsd13-amd64:
    owner: "mansaxel@besserwisser.org"
  gentoo-amd64:
    owner: "cwills@sinenomine.net"
  gentoo-gcc-amd64:
    owner: "cwills@sinenomine.net"
  linux-rc-x86_64:
    owner: "mmeffie@sinenomine.net"
  macos10-15-x86_64:
    owner: "mbarbosa@sinenomine.net"
  macos11-x86_64:
    owner: "mbarbosa@sinenomine.net"
  macos12-x86_64:
    owner: "mbarbosa@sinenomine.net"
  opensuse12-x86_64:
    # owner:
  opensuse15-x86_64:
    owner: "mmeffie@sinenomine.net"
  opensuse-tumbleweed-i386:
    # owner:
  opensuse-tumbleweed-x86_64:
    # owner:
  sol11sparc:
    owner: "mmeffie@sinenomine.net"
  solaris114-x86-2:
    owner: "mmeffie@sinenomine.net"
  sun510_x86:
    owner: "mmeffie@sinenomine.net"
  ubuntu1610-x86_64:
    owner: "mmeffie@sinenomine.net"
  ubuntu1804-amd64:
    owner: "mmeffie@sinenomine.net"
  ubuntu2004-amd64:
    owner: "mmeffie@sinenomine.net"
  wins2019-amd64:
    owner: "asedeno@mit.edu"

afsbotcfg_builders:
  - scheduler: "gerrit"
    branch: "dev"
    worker: "aix61-rs"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        jobs: 1

  - scheduler: "gerrit"
    branch: "dev"
    worker: "alma9-amd64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "alma9-amd64-rpm"
    factory:
      name: "BuildRPMs"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "centos6-amd64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "centos73-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "centos8-amd64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "dev"
    label:  "debian8-amd64"
    worker: "debian87-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "debian9-amd64"
    factory:
      name: "UnixBuild"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "debian10-amd64"
    factory:
      name: "UnixBuild"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "debian11-amd64"
    factory:
      name: "UnixBuild"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "freebsd12-amd64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--with-afs-sysname=amd64_fbsd_122"
    env:
      MKAFS_OSTYPE: "FBSD"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "fedora33-x86_64"
    factory:
      name: "UnixBuild"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "fedora34-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "fedora35-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "gentoo-amd64"
    factory:
      name: "UnixBuildAndTest"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "gentoo-gcc-amd64"
    factory:
      name: "UnixBuildAndTest"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "macos10-15-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--enable-transarc-paths --disable-pam"
        target: "dest"
        jobs: 1

  - scheduler: "gerrit"
    branch: "dev"
    worker: "macos11-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--enable-transarc-paths --disable-pam"
        target: "dest"
        jobs: 1

  - scheduler: "gerrit"
    branch: "dev"
    worker: "macos12-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--enable-transarc-paths --disable-pam"
        target: "dest"
        jobs: 1

  - scheduler: "gerrit"
    branch: "dev"
    worker: "opensuse15-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--with-linux-kernel-build=/usr/src/linux-obj/x86_64/default"

  - scheduler: "gerrit"
    branch: "dev"
    label:  "solaris10_x86"
    worker: "sun510_x86"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--enable-transarc-paths"
        target: "dest"
        jobs: 1

  - scheduler: "gerrit"
    branch: "dev"
    label:  "solaris114_x86"
    worker: "solaris114-x86-2"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "ubuntu1610-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "ubuntu1804-amd64"
    factory:
      name: "UnixBuildAndTest"

  - scheduler: "gerrit"
    branch: "dev"
    worker: "ubuntu2004-amd64"
    factory:
      name: "UnixBuildAndTest"

  - scheduler: "gerrit"
    branch: "dev"
    label:  "wins2019_amd64_free"
    worker: "wins2019-amd64"
    factory:
      name: "WinBuild"
      args:
        arch: "amd64"
        variant: "free"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "alma9-amd64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "centos6-amd64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "centos73-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "centos8-amd64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "debian9-amd64"
    factory:
      name: "UnixBuild"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "debian10-amd64"
    factory:
      name: "UnixBuild"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "debian11-amd64"
    factory:
      name: "UnixBuild"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "freebsd12-amd64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--with-afs-sysname=amd64_fbsd_122"
    env:
      MKAFS_OSTYPE: "FBSD"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "fedora32-x86_64"
    factory:
      name: "UnixBuild"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "macos10-15-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--enable-transarc-paths --disable-pam"
        target: "dest"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "opensuse15-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--with-linux-kernel-build=/usr/src/linux-obj/x86_64/default"

  - scheduler: "gerrit"
    branch: "stable"
    label:  "solaris10_x86"
    worker: "sun510_x86"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--enable-transarc-paths"
        target: "dest"

  - scheduler: "gerrit"
    branch: "stable"
    label:  "solaris114_x86"
    worker: "solaris114-x86-2"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "ubuntu1804-amd64"
    factory:
      name: "UnixBuildAndTest"

  - scheduler: "gerrit"
    branch: "stable"
    worker: "ubuntu2004-amd64"
    factory:
      name: "UnixBuildAndTest"

  - scheduler: "gerrit"
    branch: "stable"
    label:  "wins2019_amd64_free"
    worker: "wins2019-amd64"
    factory:
      name: "WinBuild"
      args:
        arch: "amd64"
        variant: "free"

  - scheduler: "gerrit"
    branch: "stable"
    label:  "wins2019_x86_checked"
    worker: "wins2019-amd64"
    factory:
      name: "WinBuild"
      args:
        arch: "x86"
        variant: "checked"

  - scheduler: "gerrit"
    branch: "oldstable"
    worker: "centos73-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "oldstable"
    worker: "centos8-amd64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "oldstable"
    worker: "debian9-amd64"
    factory:
      name: "UnixBuild"

  - scheduler: "gerrit"
    branch: "oldstable"
    worker: "debian10-amd64"
    factory:
      name: "UnixBuild"

  - scheduler: "gerrit"
    branch: "oldstable"
    worker: "fedora32-x86_64"
    factory:
      name: "UnixBuild"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "gerrit"
    branch: "oldstable"
    label:  "solaris10_x86"
    worker: "sun510_x86"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--enable-transarc-paths"
        target: "dest"

  - scheduler: "gerrit"
    branch: "oldstable"
    label:  "solaris114_x86"
    worker: "solaris114-x86-2"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "gerrit"
    branch: "oldstable"
    worker: "ubuntu1804-amd64"
    factory:
      name: "UnixBuildAndTest"

  - scheduler: "gerrit"
    branch: "oldstable"
    worker: "ubuntu2004-amd64"
    factory:
      name: "UnixBuildAndTest"

  - scheduler: "nightly"
    branch: "dev"
    worker: "sol11sparc"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "nightly"
    branch: "dev"
    worker: "centos7-arm64"
    factory:
      name: "UnixBuildIgnoreWarnings"

  - scheduler: "nightly"
    branch: "dev"
    label:  "wins2019_amd64_checked"
    worker: "wins2019-amd64"
    factory:
      name: "WinBuild"
      args:
        arch: "amd64"
        variant: "checked"

  - scheduler: "nightly"
    branch: "dev"
    label:  "wins2019_x86_free"
    worker: "wins2019-amd64"
    factory:
      name: "WinBuild"
      args:
        arch: "x86"
        variant: "free"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora21-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora22-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--disable-kernel-module --with-afs-sysname=amd64_linux26"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora23-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--disable-kernel-module --with-afs-sysname=amd64_linux26"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora24-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--disable-kernel-module --with-afs-sysname=amd64_linux26"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora25-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--disable-kernel-module --with-afs-sysname=amd64_linux26"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora26-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--disable-kernel-module --with-afs-sysname=amd64_linux26"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora27-x86_64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--disable-kernel-module --with-afs-sysname=amd64_linux26"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora28-x86_64"
    factory:
      name: "UnixBuild"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora29-x86_64"
    factory:
      name: "UnixBuild"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora30-x86_64"
    factory:
      name: "UnixBuild"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "fedora31-x86_64"
    factory:
      name: "UnixBuild"
    env:
      CFLAGS: "-Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
               -Wno-error=array-bounds -Wno-error=implicit-function-declaration"

  - scheduler: "parked"
    branch: "dev"
    worker: "freebsd13-amd64"
    factory:
      name: "UnixBuildIgnoreWarnings"
      args:
        extra_configure: "--with-afs-sysname=amd64_linux26"
