---
dependency:
  name: galaxy

platforms:
  - name: afsbotcfg-master
    # box: generic/centos7
    proxmox_template_name: centos7
    groups:
      - openafs_buildbot_masters

provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 0
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    group_vars:
      openafs_buildbot_masters:
        _merge:
          afsbotcfg_project:
            title: "Molecule Test"
            summary_title: "Molecule Test Buildbot"
        _override:
          afsbotcfg_admin_passwords:
            - ["admin@example.com", "secret"]
          afsbotcfg_worker_passwords:
            __default__: "secret"

verifier:
  name: ansible
